Others entities editor
chunchunmaru34/cinema-admin pull request #10
Opened 2018-03-14 12:20 UTC by chunchunmaru34

Added editors for users (only deleting and role changing), seats types and additional services.

2018-03-20 19:18 UTC, MikhailMartsinovich requested changes

2018-03-20 19:18 UTC, MikhailMartsinovich commented on src/app/seats-types/seats-types.component.ts
> +      .subscribe(() => this.getSeatsTypes());
здесь нужно создавать анонимную функцию?

2018-03-20 19:18 UTC, MikhailMartsinovich commented on src/app/seats-types/seats-types.component.ts
> +        .subscribe(() => this.getSeatsTypes());
здесь нужно создавать анонимную функцию?

2018-03-20 19:18 UTC, MikhailMartsinovich commented on src/app/additional-services/additions.component.ts
> +      .subscribe(() => this.getAdditions());
здесь нужно создавать анонимную функцию?
Проверь и, если можно не создавать, убери по всему проекту.

2018-03-22 06:47 UTC, chunchunmaru34 commented on src/app/additional-services/additions.component.ts
> +      .subscribe(() => this.getAdditions());
если передать функцию напрямую, то потеряется this.

2018-03-24 15:08 UTC, merged